"use client";

import { useMemo, useState } from "react";

type Language = "mn" | "en";
type AccountMode = "b2c" | "b2b";
type AuthMode = "signin" | "register" | "otp";
type Product = { id: string; name: string; category: string; price: number; image: string; note: string };

const products: Product[] = [
  { id: "seed", name: "Bity Seed", category: "Жигнэмэг", price: 8800, image: "/legacy/assets/products-texture-Def4-lGY.jpg", note: "Олон төрлийн үр, овьёостой" },
  { id: "fit", name: "Bity Fit", category: "Жигнэмэг", price: 9200, image: "/legacy/assets/products-bread-827gvz_9.jpg", note: "Овьёос, цангис, бурамтай" },
  { id: "bite", name: "Bity Bite", category: "Жигнэмэг", price: 8500, image: "/legacy/assets/products-pastry-DzYn-Waa.jpg", note: "Какао, ванилийн зөөлөн амт" },
  { id: "pastry", name: "Цөцгийн шанзтай жигнэмэл", category: "Жигнэмэл", price: 10500, image: "/assets/craftsmanship-DEMkgtJ9.jpg", note: "Шинэхэн, зөөлөн бүтэцтэй" },
  { id: "traditional", name: "Уламжлалт амт", category: "Уламжлалт", price: 9800, image: "/assets/history-BK6WUFUP.jpg", note: "Монгол ахуйн амтыг шинэчилсэн нь" },
  { id: "kids", name: "Kids+ Цасхан", category: "Хүүхдийн бүтээгдэхүүн", price: 7600, image: "/assets/people-BLcfpgP_.jpg", note: "Хүүхдэд зориулсан зөөлөн сонголт" },
];
const categories = ["Бүгд", "Жигнэмэг", "Жигнэмэл", "Уламжлалт", "Хүүхдийн бүтээгдэхүүн"];
const copy = {
  mn: { nav: ["Бидний тухай", "Бүтээгдэхүүн", "Үйлдвэр", "Хамтын ажиллагаа"], heroKicker: "МОНГОЛЫН ХҮНСНИЙ ҮЙЛДВЭРЛЭЛ · SINCE 2000", heroTitle: "Сэтгэлд хүрсэн амт", heroText: "Уламжлалт мэдрэмжийг орчин үеийн үйлдвэрлэлийн чанартай хослуулж, өдөр бүрийн амтыг бүтээнэ.", shop: "Дэлгүүрт орох", partner: "Хамтран ажиллах", storyTitle: "Амтыг бүтээдэг 26 жил", storyText: "Өгөөмж Архад ХХК нь Монголын хэрэглэгчдийн өдөр тутмын амтанд зориулсан бүтээгдэхүүнийг сэтгэл, стандарт, тогтвортой чанараар үйлдвэрлэдэг.", productsTitle: "Бүтээгдэхүүнээ сонгох", productsText: "B2C захиалга болон байгууллагын хэрэгцээнд тохирсон бүтээгдэхүүний сонголт.", factoryTitle: "Үр тарианаас бэлэн бүтээгдэхүүн хүртэл", factoryText: "Чанар нь зөвхөн савлагаан дээр биш, үйлдвэрлэлийн алхам бүрт бий болдог.", b2bTitle: "Таны бизнесийн найдвартай түнш", b2bText: "Дэлгүүр, кафе, ресторан, зочид буудал болон дистрибьютерүүдэд зориулсан нийлүүлэлтийн шийдэл.", signIn: "Нэвтрэх", cart: "Сагс", account: "Миний хэсэг" },
  en: { nav: ["About", "Products", "Factory", "Partnership"], heroKicker: "MONGOLIAN FOOD MANUFACTURING · SINCE 2000", heroTitle: "Made to reach the heart", heroText: "Everyday taste made with a warm heritage, modern production and dependable quality.", shop: "Shop products", partner: "Partner with us", storyTitle: "26 years of making taste", storyText: "Uguumj Arkhad creates everyday food products with care, standards and consistent quality for Mongolian families.", productsTitle: "Choose your products", productsText: "A considered range for direct orders and business partners.", factoryTitle: "From grain to finished product", factoryText: "Quality is made into every step of our process, not added at the end.", b2bTitle: "A dependable partner for your business", b2bText: "Supply solutions for stores, cafés, restaurants, hotels and distributors.", signIn: "Sign in", cart: "Cart", account: "Account" },
};
function formatMnt(value: number) { return `${new Intl.NumberFormat("mn-MN").format(value)}₮`; }

export default function UguumjArkhadPrototype() {
  const [language, setLanguage] = useState<Language>("mn");
  const [activeSection, setActiveSection] = useState("home");
  const [category, setCategory] = useState("Бүгд");
  const [cart, setCart] = useState<Record<string, number>>({});
  const [minOrder, setMinOrder] = useState(100000);
  const [accountMode, setAccountMode] = useState<AccountMode>("b2c");
  const [signedIn, setSignedIn] = useState(false);
  const [authOpen, setAuthOpen] = useState(false);
  const [authMode, setAuthMode] = useState<AuthMode>("signin");
  const [adminOpen, setAdminOpen] = useState(false);
  const [notice, setNotice] = useState("");
  const t = copy[language];
  const visibleProducts = useMemo(() => category === "Бүгд" ? products : products.filter((product) => product.category === category), [category]);
  const cartItems = products.filter((product) => cart[product.id]);
  const cartCount = Object.values(cart).reduce((sum, quantity) => sum + quantity, 0);
  const cartTotal = cartItems.reduce((sum, product) => sum + product.price * (cart[product.id] ?? 0), 0);
  const orderReady = accountMode === "b2b" || cartTotal >= minOrder;
  function scrollToSection(id: string) { setActiveSection(id); document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
  function addToCart(product: Product) { setCart((current) => ({ ...current, [product.id]: (current[product.id] ?? 0) + 1 })); setNotice(`${product.name} сагсанд нэмэгдлээ`); window.setTimeout(() => setNotice(""), 2200); }
  function updateQuantity(id: string, amount: number) { setCart((current) => { const next = Math.max(0, (current[id] ?? 0) + amount); const updated = { ...current }; if (next === 0) delete updated[id]; else updated[id] = next; return updated; }); }
  function completeDemoAuth(mode: AccountMode) { setAccountMode(mode); setSignedIn(true); setAuthOpen(false); setNotice(mode === "b2b" ? "Байгууллагын хүсэлт admin-аар баталгаажсаны дараа B2B үнэ нээгдэнэ" : "Тавтай морилно уу"); window.setTimeout(() => setNotice(""), 3000); }

  return <main className="site-shell">
    <header className="topbar"><button className="brand" onClick={() => scrollToSection("home")} aria-label="Өгөөмж Архад нүүр хуудас"><span className="brand-mark">ӨА</span><span><strong>Өгөөмж Архад</strong><small>FOOD MANUFACTURING</small></span></button><nav className="desktop-nav" aria-label="Үндсэн цэс">{t.nav.map((item, index) => <button key={item} onClick={() => scrollToSection(["about", "products", "factory", "partner"][index])}>{item}</button>)}</nav><div className="top-actions"><button className="language-toggle" onClick={() => setLanguage(language === "mn" ? "en" : "mn")}>{language.toUpperCase()} <span>↔</span> {language === "mn" ? "EN" : "MN"}</button><button className="icon-button" onClick={() => { setAuthMode("signin"); setAuthOpen(true); }} aria-label="Нэвтрэх">◎</button><button className="cart-button" onClick={() => scrollToSection("cart")} aria-label="Сагс">Сагс <b>{cartCount}</b></button></div></header>
    <section id="home" className="hero section-anchor"><div className="hero-content"><p className="eyebrow">{t.heroKicker}</p><h1>{t.heroTitle}<span>.</span></h1><p className="hero-copy">{t.heroText}</p><div className="hero-actions"><button className="button button-light" onClick={() => scrollToSection("products")}>{t.shop}<span>↗</span></button><button className="text-button light" onClick={() => scrollToSection("partner")}>{t.partner} <span>→</span></button></div><div className="hero-proof"><span>26 <small>жил</small></span><span>MN / EN <small>бүх хуудсанд</small></span><span>UB <small>хүргэлт</small></span></div></div><div className="hero-image" /><div className="hero-vertical">QUALITY / CARE / TASTE</div></section>
    <section id="about" className="story section-anchor section-pad"><div className="section-label">01 — OUR STORY</div><div className="story-grid"><div><p className="eyebrow dark">{language === "mn" ? "ӨГӨӨМЖ АРХАДЫН ТУХАЙ" : "ABOUT UGUUMJ ARKHAD"}</p><h2>{t.storyTitle}</h2></div><div><p className="lead">{t.storyText}</p><button className="text-button" onClick={() => scrollToSection("factory")}>{language === "mn" ? "Бидний түүхийг үзэх" : "Explore our story"} <span>↗</span></button></div></div><div className="stat-row"><div><strong>2000</strong><span>{language === "mn" ? "оноос хойш" : "since"}</span></div><div><strong>100%</strong><span>{language === "mn" ? "Монгол үйлдвэрлэл" : "Mongolian made"}</span></div><div><strong>MN / EN</strong><span>{language === "mn" ? "хоёр хэлтэй" : "bilingual experience"}</span></div></div></section>
    <section id="products" className="products-section section-anchor section-pad"><div className="section-heading"><div><div className="section-label">02 — THE SHOP</div><h2>{t.productsTitle}</h2></div><p>{t.productsText}</p></div><div className="category-tabs">{categories.map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="product-grid">{visibleProducts.map((product) => <article className="product-card" key={product.id}><div className="product-image"><img src={product.image} alt={product.name} /><span>{product.category}</span></div><div className="product-info"><div><h3>{product.name}</h3><p>{product.note}</p></div><strong>{formatMnt(product.price)}</strong></div><button className="add-button" onClick={() => addToCart(product)}>+ {language === "mn" ? "Сагсанд нэмэх" : "Add to cart"}</button></article>)}</div></section>
    <section id="factory" className="factory-section section-anchor"><div className="factory-image" /><div className="factory-copy"><div className="section-label">03 — THE FACTORY</div><h2>{t.factoryTitle}</h2><p>{t.factoryText}</p><div className="process-list"><div><span>01</span><strong>{language === "mn" ? "Сонголт" : "Selection"}</strong><small>{language === "mn" ? "Түүхий эдийн хяналт" : "Ingredient control"}</small></div><div><span>02</span><strong>{language === "mn" ? "Бүтээлт" : "Making"}</strong><small>{language === "mn" ? "Технологи, туршлага" : "Process and craft"}</small></div><div><span>03</span><strong>{language === "mn" ? "Итгэл" : "Trust"}</strong><small>{language === "mn" ? "Чанарын эцсийн хяналт" : "Final quality check"}</small></div></div></div></section>
    <section id="partner" className="partner-section section-anchor section-pad"><div className="partner-card"><div className="section-label">04 — PARTNERSHIP</div><h2>{t.b2bTitle}</h2><p>{t.b2bText}</p><div className="partner-actions"><button className="button button-dark" onClick={() => { setAccountMode("b2b"); setAuthMode("register"); setAuthOpen(true); }}>{language === "mn" ? "B2B бүртгэл үүсгэх" : "Create B2B account"} <span>↗</span></button><button className="text-button" onClick={() => { setNotice("Каталог татах хэсэг prototype-д бэлэн"); window.setTimeout(() => setNotice(""), 2400); }}>{language === "mn" ? "Каталог татах" : "Download catalogue"} ↓</button></div></div><div className="partner-side"><span className="big-quote">“</span><p>{language === "mn" ? "Сайн бүтээгдэхүүн бол сайн түншлэлийн эхлэл." : "Good products are the beginning of good partnerships."}</p><span className="signature">UGUUMJ ARKHAD</span></div></section>
    <section id="cart" className="cart-section section-anchor section-pad"><div className="section-heading"><div><div className="section-label">05 — YOUR ORDER</div><h2>{t.cart}</h2></div><p>{accountMode === "b2b" ? "B2B account · Company ordering" : `B2C ${language === "mn" ? "захиалга" : "order"}`}</p></div><div className="cart-layout"><div className="cart-list">{cartItems.length === 0 ? <div className="empty-cart"><span>🛒</span><h3>{language === "mn" ? "Сагс одоогоор хоосон байна" : "Your cart is empty"}</h3><button className="text-button" onClick={() => scrollToSection("products")}>{language === "mn" ? "Бүтээгдэхүүн үзэх" : "Browse products"} →</button></div> : cartItems.map((product) => <div className="cart-row" key={product.id}><img src={product.image} alt="" /><div><h3>{product.name}</h3><small>{formatMnt(product.price)}</small></div><div className="quantity"><button onClick={() => updateQuantity(product.id, -1)}>-</button><b>{cart[product.id]}</b><button onClick={() => updateQuantity(product.id, 1)}>+</button></div><strong>{formatMnt(product.price * (cart[product.id] ?? 0))}</strong></div>)}</div><aside className="cart-summary"><div><span>{language === "mn" ? "Захиалгын дүн" : "Order subtotal"}</span><strong>{formatMnt(cartTotal)}</strong></div>{accountMode === "b2c" && <><div className="minimum-line"><span>{language === "mn" ? "Доод захиалга" : "Minimum order"}</span><strong>{formatMnt(minOrder)}</strong></div><div className="progress"><span style={{ width: `${Math.min(100, (cartTotal / minOrder) * 100)}%` }} /></div><small>{orderReady ? (language === "mn" ? "Захиалга хийхэд бэлэн" : "Ready to checkout") : `${formatMnt(Math.max(0, minOrder - cartTotal))} ${language === "mn" ? "нэмж сонгоно уу" : "more to checkout"}`}</small></>}{accountMode === "b2b" && <div className="b2b-badge">B2B account · Wholesale pricing</div>}<button className="button button-dark full-width" disabled={!orderReady || cartItems.length === 0} onClick={() => setNotice("Захиалга амжилттай үүсгэх prototype урсгал нээгдлээ")}>{language === "mn" ? "Захиалга үргэлжлүүлэх" : "Continue to checkout"} <span>↗</span></button><div className="payment-row"><span>QPay</span><span>Card</span><span>Bank</span><span>COD</span></div></aside></div></section>
    <section className="reba-strip"><div><span className="eyebrow dark">A SEPARATE EXPERIENCE</span><h2>REBA<br /><em>Vintage Café</em></h2></div><div><p>{language === "mn" ? "Кофе, амттан, уулзалт — REBA-ийн тусдаа сайтыг удахгүй холбоно." : "Coffee, food and gatherings — the separate REBA site will be connected soon."}</p><button className="text-button" onClick={() => setNotice("REBA Vintage Café тусдаа сайт удахгүй холбогдоно")}>{language === "mn" ? "REBA-г үзэх" : "Visit REBA"} ↗</button></div></section>
    <footer className="footer"><div className="brand footer-brand"><span className="brand-mark">ӨА</span><span><strong>Өгөөмж Архад</strong><small>СЭТГЭЛД ХҮРСЭН АМТ</small></span></div><div><span>Нарны гүүрний баруун урд · Улаанбаатар</span><span>info@uguumj-arkhad.mn</span></div><div className="footer-controls"><button onClick={() => setAdminOpen(true)}>Admin demo</button><button onClick={() => { setAuthMode("signin"); setAuthOpen(true); }}>{signedIn ? t.account : t.signIn}</button></div></footer>
    <div className="mobile-nav"><button className={activeSection === "home" ? "active" : ""} onClick={() => scrollToSection("home")}>⌂<small>Нүүр</small></button><button onClick={() => scrollToSection("products")}>⌕<small>Дэлгүүр</small></button><button onClick={() => scrollToSection("cart")}>▢<b>{cartCount}</b><small>Сагс</small></button><button onClick={() => { setAuthMode("signin"); setAuthOpen(true); }}>◎<small>Профайл</small></button></div>
    {notice && <div className="toast">{notice}<button onClick={() => setNotice("")}>×</button></div>}
    {authOpen && <div className="modal-backdrop" onClick={() => setAuthOpen(false)}><div className="auth-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setAuthOpen(false)}>×</button><span className="eyebrow dark">UGUUMJ ARKHAD ACCOUNT</span><h2>{authMode === "register" ? "Бүртгэл үүсгэх" : authMode === "otp" ? "OTP баталгаажуулах" : "Тавтай морилно уу"}</h2>{authMode === "otp" ? <><p>Таны утсанд илгээсэн 6 оронтой кодыг оруулна уу.</p><input className="field" placeholder="000 000" /><button className="button button-dark full-width" onClick={() => completeDemoAuth(accountMode)}>Баталгаажуулах</button></> : <><div className="account-switch"><button className={accountMode === "b2c" ? "active" : ""} onClick={() => setAccountMode("b2c")}>B2C хэрэглэгч</button><button className={accountMode === "b2b" ? "active" : ""} onClick={() => setAccountMode("b2b")}>B2B байгууллага</button></div>{authMode === "register" && accountMode === "b2b" && <div className="company-note">Байгууллагын нэр, регистр, ажилтнуудын эрхийг admin баталгаажуулна.</div>}<div className="social-buttons"><button onClick={() => completeDemoAuth(accountMode)}><span className="google">G</span> Google-ээр үргэлжлүүлэх</button><button onClick={() => completeDemoAuth(accountMode)}><span className="facebook">f</span> Facebook-ээр үргэлжлүүлэх</button></div><div className="or"><span>эсвэл</span></div><input className="field" placeholder="Email хаяг" type="email" /><input className="field" placeholder="Нууц үг" type="password" />{authMode === "register" && accountMode === "b2b" && <input className="field" placeholder="Компанийн нэр" />}<button className="button button-dark full-width" onClick={() => completeDemoAuth(accountMode)}>{authMode === "register" ? "Бүртгүүлэх" : "Email-ээр нэвтрэх"}</button><button className="otp-link" onClick={() => setAuthMode("otp")}>Утасны OTP-ээр нэвтрэх →</button><button className="switch-auth" onClick={() => setAuthMode(authMode === "signin" ? "register" : "signin")}>{authMode === "signin" ? "Шинэ account үүсгэх" : "Нэвтрэх хэсэг рүү буцах"}</button></>}</div></div>}
    {adminOpen && <div className="modal-backdrop" onClick={() => setAdminOpen(false)}><div className="admin-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setAdminOpen(false)}>×</button><span className="eyebrow dark">ADMIN CONTROL CENTER</span><h2>Shop тохиргоо</h2><p>B2C хэрэглэгчийн захиалгын доод үнийн дүнг admin энд өөрчилнө.</p><label className="admin-label">Доод захиалгын дүн<input className="field" type="number" value={minOrder} onChange={(event) => setMinOrder(Number(event.target.value))} /></label><div className="admin-preview"><span>Одоогийн тохиргоо</span><strong>{formatMnt(minOrder)}</strong></div><button className="button button-dark full-width" onClick={() => { setAdminOpen(false); setNotice("Admin тохиргоо шинэчлэгдлээ"); }}>Хадгалах</button></div></div>}
  </main>;
}
